//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaRun.Entity.SteelMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMC_ProcessManagement
    {
        public int ProcessId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> TreeId { get; set; }
        public Nullable<System.DateTime> ProduceStartDate { get; set; }
        public Nullable<System.DateTime> ProduceEndDate { get; set; }
        public Nullable<int> MemberCompanyId { get; set; }
        public Nullable<int> IsSetUpProcessingTask { get; set; }
        public string SetUpProcessing { get; set; }
        public Nullable<int> SetUpProcessingDays { get; set; }
        public Nullable<int> IsSetUpProcessing { get; set; }
        public Nullable<int> IsSubmergedArcProcessingTask { get; set; }
        public string SubmergedArcProcessing { get; set; }
        public Nullable<int> SubmergedArcProcessingDays { get; set; }
        public Nullable<int> IsSubmergedArcProcessing { get; set; }
        public Nullable<int> IsRivetingProcessingTask { get; set; }
        public string RivetingProcessing { get; set; }
        public Nullable<int> RivetingProcessingDays { get; set; }
        public Nullable<int> IsRivetingProcessing { get; set; }
        public Nullable<int> IsPaintProcessingTask { get; set; }
        public string PaintProcessing { get; set; }
        public Nullable<int> PaintProcessingDays { get; set; }
        public Nullable<int> IsPaintProcessing { get; set; }
        public Nullable<int> QualityInspection { get; set; }
        public Nullable<int> Supervision { get; set; }
        public Nullable<int> UnqualifiedNumber { get; set; }
        public Nullable<int> QualifiedNumber { get; set; }
        public Nullable<int> IsPacking { get; set; }
        public string Packing { get; set; }
        public Nullable<int> PackingDays { get; set; }
        public string Description { get; set; }
        public string OrderNumbering { get; set; }
    }
}
