//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaRun.Entity.SteelMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMC_Collar
    {
        public int CollarId { get; set; }
        public Nullable<int> TreeId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string MemberName { get; set; }
        public string MemberModel { get; set; }
        public string MemberUnit { get; set; }
        public Nullable<int> CollarNumber { get; set; }
        public string Use { get; set; }
        public Nullable<System.DateTime> CollarTime { get; set; }
        public string Librarian { get; set; }
        public string CollarMan { get; set; }
        public string Description { get; set; }
    }
}
