//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaRun.Entity.SteelMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public int TestId { get; set; }
        public int Code { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserName { get; set; }
        public string Remark { get; set; }
    }
}
