2017-06-09 08:12:09,608 [20] ERROR LeaRun.DataAccess.DbHelper - 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到)
2017-06-09 11:22:19,749 [96] ERROR LeaRun.DataAccess.DbHelper - 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到)
2017-06-09 16:36:52,731 [268] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:37:25,565 [308] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:37:59,038 [234] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:39:17,561 [318] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:40:05,378 [295] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:40:44,410 [327] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:42:14,024 [245] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:42:45,810 [355] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:43:38,232 [302] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:44:20,263 [308] ERROR LeaRun.DataAccess.DbHelper - 执行超时已过期。完成操作之前已超时或服务器未响应。 
2017-06-09 16:52:04,556 [345] ERROR LeaRun.DataAccess.DbHelper - 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到)
