2017-05-11 21:34:34,896 [416] ERROR LeaRun.DataAccess.DbHelper - 列名 'ResponsibleProject' 无效。
2017-05-11 21:34:36,399 [273] ERROR LeaRun.DataAccess.DbHelper - 列名 'ResponsibleProject' 无效。
2017-05-11 22:08:28,901 [34] ERROR LeaRun.DataAccess.DbHelper - “.”附近有语法错误。
2017-05-11 22:08:33,278 [34] ERROR LeaRun.DataAccess.DbHelper - “.”附近有语法错误。
2017-05-11 22:08:33,824 [121] ERROR LeaRun.DataAccess.DbHelper - “.”附近有语法错误。
2017-05-11 22:08:34,240 [34] ERROR LeaRun.DataAccess.DbHelper - “.”附近有语法错误。
2017-05-11 22:08:34,712 [52] ERROR LeaRun.DataAccess.DbHelper - “.”附近有语法错误。
2017-05-11 22:08:35,002 [34] ERROR LeaRun.DataAccess.DbHelper - “.”附近有语法错误。
