2017-06-06 00:31:16,496 [58] ERROR LeaRun.DataAccess.DbHelper - 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到)
2017-06-06 08:53:30,287 [7] ERROR LeaRun.DataAccess.DbHelper - 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到)
2017-06-06 09:39:24,953 [48] ERROR LeaRun.DataAccess.DbHelper - 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到)
2017-06-06 10:45:15,666 [18] ERROR LeaRun.DataAccess.DbHelper - 在从服务器接收结果时发生传输级错误。 (provider: TCP Provider, error: 0 - 信号灯超时时间已到)
